### ISSUE TITLE
Windows CI build likely does not work

### ISSUE THREAD

**Issue by CouleeApps** [emesare/binja-msvc#21]
I see you have based the github actions build for this off of https://github.com/CouleeApps/binja-ci-tests/blob/master/binja.patch and I just wanted to let you know that the Windows build this patch produces does not actually work... https://github.com/CouleeApps/binja-ci-tests/issues/1 

I haven't had time to go figure out what the correct solution is, but just a heads up in advance that this is a known issue.

**Comment by emesare** [comment]
Thanks for opening the issue, my temporary solution has been manually building it and replacing the broken one.

**Comment by CouleeApps** [comment]
Latest updates to the base repo should support building on windows. I migrated it to https://github.com/Vector35/sample_plugin_cpp (which apparently breaks github actions, thanks github). Let me know if those changes get this repo to work, and if you run into any issues along the way :)

**Comment by emesare** [comment]
> Latest updates to the base repo should support building on windows. I migrated it to https://github.com/Vector35/sample_plugin_cpp ~(which apparently breaks github actions, thanks github)~. Let me know if those changes get this repo to work, and if you run into any issues along the way :)

Fixed! Thanks again :)
